services:
  minio:
    container_name: minio
    image: minio/minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data
    volumes:
      - injestion_data:/data

volumes:
  injestion_data:
    external: true
    name: minio_minio_data

